server:
  port: 9000

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        #route mapping
      - id: customer-service
        uri: http://192.168.0.102:8083
        predicates:
        - Path= /**
        
      - id: station
        uri: http://192.168.0.102:8081
        predicates:
        - Path= /**